/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.riyadhplaces.ui;

import com.riyadhplaces.dao.DrinkDAO;
import com.riyadhplaces.dao.MySQLDrinkDAO;
import com.riyadhplaces.dao.MySQLRestaurantDAO;
import com.riyadhplaces.dao.RestaurantDAO;
import com.riyadhplaces.entities.Drink;
import com.riyadhplaces.entities.Restaurant;
import com.riyadhplaces.exceptions.DAOException;
import com.riyadhplaces.support.QueryBuilder;
import com.riyadhplaces.ui.common.Alert;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alhza
 */
public class AddFrame extends javax.swing.JFrame {

    public AddFrame() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        getContentPane().setBackground(Color.decode("#FCF8E8"));

        SelectTypeD.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SelectPlace = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        resTypeCB = new javax.swing.JComboBox<>();
        SelectTypeD = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        placeAddressField1 = new javax.swing.JTextField();
        phoneNumberfiled1 = new javax.swing.JTextField();
        placeTypeField = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        placeNameField1 = new javax.swing.JTextField();
        placeNameField = new javax.swing.JTextField();
        NameField1 = new javax.swing.JTextField();
        phoneNumberfiled = new javax.swing.JTextField();
        placeAddressField = new javax.swing.JTextField();
        Back = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Riyadh Places");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(Color.decode("#94B49F"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 0, 204, 25));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 236, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Home  ");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 40, -1));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("--->");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Add");
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jLabel40.setText("--->");
        jPanel3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 70));

        jPanel5.setBackground(Color.decode("#FCF8E8")
        );
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Contact us");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 106, -1));

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Developed by ");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, -1));

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Munirah Alsubaie");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, -1));

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Hatoon Albadah");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 87, -1));

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("|");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 10, -1));
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 31, 40, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/riyadhplaces/icons/icons/icons8-instagram-25-Brown.png"))); // NOI18N
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/riyadhplaces/icons/icons/icons8-twitter-circled-25.png"))); // NOI18N
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 30, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 730, 60));

        jPanel10.setBackground(Color.decode("#DFE8CC")
        );
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 68, 40, -1));

        jLabel3.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Select Type:");
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 80, 20));

        SelectPlace.setBackground(Color.decode("#ECB390"));
        SelectPlace.setForeground(Color.decode("#ECB390")
        );
        SelectPlace.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Restaurants", "Drinks", " " }));
        SelectPlace.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SelectPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectPlaceActionPerformed(evt);
            }
        });
        jPanel10.add(SelectPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 100, -1));

        jLabel4.setText("jLabel4");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 64, -1, 0));

        resTypeCB.setBackground(Color.decode("#ECB390"));
        resTypeCB.setForeground(Color.decode("#ECB390"));
        resTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Italian ", "Japaneses ", " " }));
        resTypeCB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resTypeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resTypeCBActionPerformed(evt);
            }
        });
        jPanel10.add(resTypeCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 100, 20));

        SelectTypeD.setBackground(Color.decode("#ECB390"));
        SelectTypeD.setForeground(Color.decode("#ECB390")
        );
        SelectTypeD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cafes", "Juices" }));
        SelectTypeD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SelectTypeD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectTypeDActionPerformed(evt);
            }
        });
        jPanel10.add(SelectTypeD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 100, 20));

        jLabel12.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText(" Name:");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Phone Number:");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        jLabel15.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Address:");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 60, 20));

        placeAddressField1.setForeground(new java.awt.Color(102, 102, 102));
        placeAddressField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeAddressField1ActionPerformed(evt);
            }
        });
        jPanel10.add(placeAddressField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 100, -1));

        phoneNumberfiled1.setForeground(new java.awt.Color(102, 102, 102));
        phoneNumberfiled1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberfiled1ActionPerformed(evt);
            }
        });
        jPanel10.add(phoneNumberfiled1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 100, -1));

        placeTypeField.setForeground(new java.awt.Color(102, 102, 102));
        placeTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeTypeFieldActionPerformed(evt);
            }
        });
        jPanel10.add(placeTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 100, -1));

        jButtonAdd.setBackground(Color.decode("#ECB390"));
        jButtonAdd.setText("Save");
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel10.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 100, -1));

        jLabel20.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Name:");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 40, 20));
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jLabel22.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Select Place:");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 80, 20));

        jLabel23.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Type:");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 40, 20));

        jLabel25.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Address:");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, 10));

        jLabel26.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Phone Number:");
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        placeNameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeNameField1ActionPerformed(evt);
            }
        });
        jPanel10.add(placeNameField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 100, -1));

        placeNameField.setForeground(new java.awt.Color(102, 102, 102));
        placeNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeNameFieldActionPerformed(evt);
            }
        });
        jPanel10.add(placeNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 100, -1));

        NameField1.setForeground(new java.awt.Color(102, 102, 102));
        NameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameField1ActionPerformed(evt);
            }
        });
        jPanel10.add(NameField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 100, -1));

        phoneNumberfiled.setForeground(new java.awt.Color(102, 102, 102));
        phoneNumberfiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberfiledActionPerformed(evt);
            }
        });
        jPanel10.add(phoneNumberfiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 100, -1));

        placeAddressField.setForeground(new java.awt.Color(102, 102, 102));
        placeAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeAddressFieldActionPerformed(evt);
            }
        });
        jPanel10.add(placeAddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 100, -1));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 660, 280));

        Back.setBackground(Color.decode("#ECB390")
        );
        Back.setText("Back");
        Back.setBorder(null);
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        hide();
        MainFrame frame = new MainFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked

        RestaurantFrame frame = new RestaurantFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_jLabel30MouseClicked

    private void SelectPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectPlaceActionPerformed

        SelectTypeD.setVisible(false);
        resTypeCB.setVisible(false);
        int SelectIndex = SelectPlace.getSelectedIndex();
        if (SelectIndex == 0) {
            resTypeCB.setVisible(true);
        } else {
            SelectTypeD.setVisible(true);

        }
    }//GEN-LAST:event_SelectPlaceActionPerformed

    private void placeAddressField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeAddressField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placeAddressField1ActionPerformed

    private void phoneNumberfiled1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberfiled1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberfiled1ActionPerformed

    private void placeTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placeTypeFieldActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed

        Drink drink = new Drink();
        DrinkDAO drinkDAO = new MySQLDrinkDAO();

        Restaurant restaurant = new Restaurant();
        RestaurantDAO rDAO = new MySQLRestaurantDAO();

        try {
            String Type = resTypeCB.getSelectedItem().toString();
            String Name = placeNameField.getText();
            String Address = placeAddressField.getText();

            if (Type.equals("")) {
                Alert.error(this.getRootPane(), "Type can't be null", "Add Type");
                return;
            }
            if (Name.equals("")) {
                Alert.error(this.getRootPane(), "Name can't be null", "Add Name");
                return;
            }
            if (Address.equals("")) {
                Alert.error(this.getRootPane(), "Address can't be null", "Add Address");
                return;
            }

            if (phoneNumberfiled.getText().length() <= 0) {
                Alert.error(this.getRootPane(), "Phone Number can't be null", "Add Phone");
                return;
            }

            Long Phone = Long.parseLong(phoneNumberfiled.getText());
            if (SelectPlace.getSelectedIndex() == 0) {
                rDAO.insert(new Restaurant(Type, Name, Address, Phone));

            } else {
                Type = SelectTypeD.getSelectedItem().toString();
                drinkDAO.insert(new Drink(Type, Name, Address, Phone));
            }

            JOptionPane.showMessageDialog(rootPane, "Successfully Added");
            placeTypeField.setText(Type);
            placeNameField1.setText(Name);
            placeAddressField1.setText(Address);
            String phone = Phone.toString();
            phoneNumberfiled1.setText(phone);

        } catch (DAOException ex) {
            Alert.error(this.getRootPane(), ex.getMessage(), "Add Place");

        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        hide();
        MainFrame frame = new MainFrame();
        frame.setVisible(false);

    }//GEN-LAST:event_BackActionPerformed

    private void SelectTypeDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectTypeDActionPerformed

    }//GEN-LAST:event_SelectTypeDActionPerformed

    private void resTypeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resTypeCBActionPerformed

    }//GEN-LAST:event_resTypeCBActionPerformed

    private void placeNameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeNameField1ActionPerformed

    }//GEN-LAST:event_placeNameField1ActionPerformed

    private void placeNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placeNameFieldActionPerformed

    private void NameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameField1ActionPerformed

    private void phoneNumberfiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberfiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberfiledActionPerformed

    private void placeAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placeAddressFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField NameField1;
    private javax.swing.JComboBox<String> SelectPlace;
    private javax.swing.JComboBox<String> SelectTypeD;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField phoneNumberfiled;
    private javax.swing.JTextField phoneNumberfiled1;
    private javax.swing.JTextField placeAddressField;
    private javax.swing.JTextField placeAddressField1;
    private javax.swing.JTextField placeNameField;
    private javax.swing.JTextField placeNameField1;
    private javax.swing.JTextField placeTypeField;
    private javax.swing.JComboBox<String> resTypeCB;
    // End of variables declaration//GEN-END:variables
}
